harmonazingbeer/cloud/urls.py
from django.conf.urls import url
from . import views

app_name = 'cloud'
urlpatterns = [
    #1 - Views de Cadastros
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^beer$', views.IndexOnView, name='indexOn'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    #1.1 Address
    url(r'^pais/$', views.PaisView, name='pais'),
    url(r'^regiao/$', views.RegiaoView, name='regiao'),
    url(r'^estado/$', views.EstadoView, name='estado'),
    url(r'^cidade/$', views.CidadeView, name='cidade'),
    #1.2 Beer
    url(r'^tipo/$', views.TipoView, name='tipo'),
    url(r'^cor/$', views.CorView, name='cor'),
    url(r'^rotulo/$', views.RotuloView, name='rotulo'),
    #1.3 Person
    url(r'^usuario/$', views.UsuarioView, name='usuario'),
    url(r'^usuarioNew/$', views.UsuarioNewView.as_view(), name='usuarioNew'),
    url(r'^fabricante/$', views.FabricanteView, name='fabricante'),
    url(r'^estabelecimento/$', views.EstabelecimentoView, name='estabelecimento'),
    #1.4 Food
    url(r'^comida/$', views.ComidaView, name='comida'),
    url(r'^prato/$', views.PratoView, name='prato'),
    url(r'^acompanhamento/$', views.AcompanhamentoView, name='acompanhamento'),
    #1.5 Harmonize
    url(r'^Sugestao/$', views.sugestaoView, name='sugestao'),
    url(r'^Nota/$', views.notaView, name='nota'),
    url(r'^Peso/$', views.pesoView, name='peso'),

    #2 - Views de ações
    url(r'^logar/$', views.login, name='logar'),
    url(r'^deslogar/$', views.sair, name='sair'),
    #2.1 Address
    url(r'^cadastrarPais/$', views.cadastrarPais, name='cadastrarPais'),
    url(r'^cadastrarRegiao/$', views.cadastrarRegiao, name='cadastrarRegiao'),
    url(r'^cadastrarEstado/$', views.cadastrarEstado, name='cadastrarEstado'),
    url(r'^cadastrarCidade/$', views.cadastrarCidade, name='cadastrarCidade'),
    #2.1.1 deletes
    url(r'^deletePais/$', views.toDeletePais, name='deletePais'),
    url(r'^deleteRegiao/$', views.toDeleteRegiao, name='deleteRegiao'),
    url(r'^deleteEstado/$', views.toDeleteEstado, name='deleteEstado'),
    url(r'^deleteCidade/$', views.toDeleteCidade, name='deleteCidade'),
    #2.2 Beer
    url(r'^cadastrarCor/$', views.cadastrarCor, name='cadastrarCor'),
    url(r'^cadastrarTipo/$', views.cadastrarTipo, name='cadastrarTipo'),
    url(r'^cadastrarRotulo/$', views.cadastrarRotulo, name='cadastrarRotulo'),
    url(r'^cadastrarCartaCerveja/$', views.cadastrarCartaCerveja, name='cadastrarCartaCerveja'),
    #2.2.1 deletes
    url(r'^deleteCor/$', views.toDeleteCor, name='deleteCor'),
    url(r'^deleteTipo/$', views.toDeleteTipo, name='deleteTipo'),
    url(r'^deleteRotulo/$', views.toDeleteRotulo, name='deleteRotulo'),
    #url(r'^deleteCartaCerveja/$', views.toDeleteCarta, name='deleteCartaCerveja'),
    #2.3 Person
    url(r'^cadastrarUsuario/$', views.cadastrarUsuario, name='cadastrarUsuario'),
    url(r'^cadastrarFabricante/$', views.cadastrarFabricante, name='cadastrarFabricante'),
    url(r'^cadastrarEstabelecimento/$', views.cadastrarEstabelecimento, name='cadastrarEstabelecimento'),
    #2.3.1 Deletes
    url(r'^deleteUsuario/$', views.toDeleteUsuario, name='deleteUsuario'),
    url(r'^deleteFabricante/$', views.toDeleteFabricante, name='deleteFabricante'),
    url(r'^deleteEstabelecimento/$', views.toDeleteEstabelecimento, name='deleteEstabelecimento'),
    #2.4 Food
    url(r'^cadastrarComida/$', views.cadastrarComida, name='cadastrarComida'),
    url(r'^cadastrarPrato/$', views.cadastrarPrato, name='cadastrarPrato'),
    url(r'^cadastrarAcompanhamento/$', views.cadastrarAcompanhamento, name='cadastrarAcompanhamento'),    
    #2.4.1 Deletes
    url(r'^deleteComida/$', views.toDeleteComida, name='deleteComida'),
    url(r'^deletePrato/$', views.toDeletePrato, name='deletePrato'),
    url(r'^deleteAcompanhamento/$', views.toDeleteAcompanhamento, name='deleteAcompanhamento'),
    #2.5 Harmonize
    url(r'^gerarSugestao/$', views.gerarSugestao, name='gerarSugestao'),
    url(r'^gravarRotuloSelecionado/$', views.gravarRotuloSelecionado, name='gravarRotuloSelecionado'),
    url(r'^gravarNota/$', views.gravarNota, name='gravarNota'),
    url(r'^gravarPeso/$', views.gravarPeso, name='gravarPeso'),
]

harmonazingbeer/harmonazingbeer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^cloud/', include('cloud.urls')),
    url(r'^admin/', admin.site.urls),
]

harmonazingbeer/cloud/views/view_Address.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.contrib.auth.decorators import login_required
from ..models.model_Address import *

# Cadastro de Pais
@login_required
def PaisView(request):
    latest_pais_list = Pais.objects.order_by('-nome')[:30]
    latest_continente_list = Continente.objects.order_by('nome')

    if len(latest_continente_list) < 1:
        Continente.PopularBanco()
        latest_continente_list = Continente.objects.order_by('nome')

    template = loader.get_template('cloud/cadPais.html')
    context = {
        'latest_pais_list':latest_pais_list,
        'latest_continente_list':latest_continente_list,
    }
    return HttpResponse(template.render(context, request))

@login_required
def cadastrarPais(request):
    try:
        pais = Pais()
        pais.nome = request.POST['nome']
        pais.continente = get_object_or_404(Continente, pk=request.POST['continente'])
        pais.save()
    except:
        return HttpResponseRedirect(reverse('cloud:pais'))
    else:
        return HttpResponseRedirect(reverse('cloud:pais'))

@login_required
def toDeletePais(request):
    try:
        pais = get_object_or_404(Pais, id=request.POST['id'])
        pais.delete()
    except:
        return HttpResponseRedirect(reverse('cloud:pais'))
    else:
        return HttpResponseRedirect(reverse('cloud:pais'))


# Cadastro de Região
@login_required
def RegiaoView(request):
    latest_regiao_list = Regiao.objects.order_by('-nome')[:30]
    latest_clima_list = Clima.objects.order_by('nome')
    latest_pais_list = Pais.objects.order_by('nome')

    if len(latest_clima_list) < 1:
        Clima.PopularBanco()
        latest_clima_list = Clima.objects.order_by('nome')

    template = loader.get_template('cloud/cadRegiao.html')
    context = {
        'latest_regiao_list':latest_regiao_list,
        'latest_clima_list':latest_clima_list,
        'latest_pais_list':latest_pais_list,
    }
    return HttpResponse(template.render(context, request))

@login_required
def cadastrarRegiao(request):
    try:
        regiao = Regiao()
        regiao.nome = request.POST['nome']
        regiao.pais = get_object_or_404(Pais, pk=request.POST['pais'])
        regiao.clima = get_object_or_404(Clima, pk=request.POST['clima'])
        regiao.save()
    except:
        return HttpResponseRedirect(reverse('cloud:regiao'))
    else:
        return HttpResponseRedirect(reverse('cloud:regiao'))

@login_required
def toDeleteRegiao(request):
    try:
        regiao = get_object_or_404(Regiao, id=request.POST['id'])
        regiao.delete()
    except:
        return HttpResponseRedirect(reverse('cloud:regiao'))
    else:
        return HttpResponseRedirect(reverse('cloud:regiao'))

# Cadastro de Estado
@login_required
def EstadoView(request):
    latest_estado_list = Estado.objects.order_by('-nome')[:30]
    latest_clima_list = Clima.objects.order_by('nome')
    latest_regiao_list = Regiao.objects.order_by('nome')
    template = loader.get_template('cloud/cadEstado.html')
    context = {
        'latest_estado_list':latest_estado_list,
        'latest_clima_list':latest_clima_list,
        'latest_regiao_list':latest_regiao_list,
    }
    return HttpResponse(template.render(context, request))

@login_required
def cadastrarEstado(request):
    try:
        estado = Estado()
        estado.nome = request.POST['nome']
        estado.regiao = get_object_or_404(Regiao, pk=request.POST['regiao'])
        estado.clima = get_object_or_404(Clima, pk=request.POST['clima'])
        estado.save()
    except:
        return HttpResponseRedirect(reverse('cloud:estado'))
    else:
        return HttpResponseRedirect(reverse('cloud:estado'))

@login_required
def toDeleteEstado(request):
    try:
        estado = get_object_or_404(Estado, id=request.POST['id'])
        estado.delete()
    except:
        return HttpResponseRedirect(reverse('cloud:estado'))
    else:
        return HttpResponseRedirect(reverse('cloud:estado'))

# Cadastro de Cidade
@login_required
def CidadeView(request):
    latest_cidade_list = Cidade.objects.order_by('-nome')[:30]
    latest_clima_list = Clima.objects.order_by('nome')
    latest_estado_list = Estado.objects.order_by('nome')
    template = loader.get_template('cloud/cadCidade.html')
    context = {
        'latest_cidade_list':latest_cidade_list,
        'latest_clima_list':latest_clima_list,
        'latest_estado_list':latest_estado_list,
    }
    return HttpResponse(template.render(context, request))

@login_required
def cadastrarCidade(request):
    try:
        cidade = Cidade()
        cidade.nome = request.POST['nome']
        cidade.estado = get_object_or_404(Estado, pk=request.POST['estado'])
        cidade.clima = get_object_or_404(Clima, pk=request.POST['clima'])
        cidade.save()
    except:
        return HttpResponseRedirect(reverse('cloud:cidade'))
    else:
        return HttpResponseRedirect(reverse('cloud:cidade'))

@login_required
def toDeleteCidade(request):
    try:
        cidade = get_object_or_404(Cidade, id=request.POST['id'])
        cidade.delete()
    except:
        return HttpResponseRedirect(reverse('cloud:cidade'))
    else:
        return HttpResponseRedirect(reverse('cloud:cidade'))

harmonazingbeer/cloud/views/view_Beer.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.contrib.auth.decorators import login_required
from ..models.model_Beer import *
from ..models.model_Address import Cidade
from ..models.model_Person import Fabricante, Estabelecimento
from ..sugestao.HarmonizegerarSugestao import *

#Cadastro Tipo
@login_required
def TipoView(request):
    latest_tipo_list = Tipo.objects.order_by('-nome')[:30]
    latest_cor_list = Cor.objects.order_by('nome')
    template = loader.get_template('cloud/cadTipo.html')
    context = {
        'latest_tipo_list':latest_tipo_list,
        'latest_cor_list':latest_cor_list
    }
    return HttpResponse(template.render(context, request))

@login_required
def cadastrarTipo(request):
    try:
        tipo = Tipo()
        tipo.nome = request.POST['nome']
        tipo.cor = get_object_or_404(Cor, pk=request.POST['cor'])
        tipo.save()
    except:
        return HttpResponseRedirect(reverse('cloud:tipo'))
    else:
        return HttpResponseRedirect(reverse('cloud:tipo'))

@login_required
def toDeleteTipo(request):
    try:
        tipo = get_object_or_404(Tipo, id=request.POST['id'])
        tipo.delete()
    except:
        return HttpResponseRedirect(reverse('cloud:tipo'))
    else:
        return HttpResponseRedirect(reverse('cloud:tipo'))

#Cadastro Cor
@login_required
def CorView(request):    
    template =loader.get_template('cloud/cadCor.html')
    latest_cor_list = Cor.objects.order_by('-id')[:30]
    context = {'latest_cor_list':latest_cor_list,}
    return HttpResponse(template.render(context,request))

@login_required
def cadastrarCor(request):
    try:
        cor = Cor()
        cor.nome = request.POST['nome']
        cor.save()
    except:
        return HttpResponseRedirect(reverse('cloud:cor'))
    else:
        return HttpResponseRedirect(reverse('cloud:cor'))

@login_required
def toDeleteCor(request):
    try:
        cor = get_object_or_404(Cor, id=request.POST['id'])
        cor.delete()
    except:
        return HttpResponseRedirect(reverse('cloud:cor'))
    else:
        return HttpResponseRedirect(reverse('cloud:cor'))

#cadastro Rotulo
@login_required
def RotuloView(request):    
    template =loader.get_template('cloud/cadRotulo.html')
    latest_rotulo_list = Rotulo.objects.order_by('nome')[:30]
    latest_cidade_list = Cidade.objects.order_by('nome')
    latest_fabricante_list = Fabricante.objects.order_by('nome')
    latest_tipo_list = Tipo.objects.order_by('nome')
    latest_cor_list = Cor.objects.order_by('nome')

    context = {
        'latest_rotulo_list':latest_rotulo_list,
        'latest_cidade_list':latest_cidade_list,
        'latest_fabricante_list': latest_fabricante_list,
        'latest_tipo_list': latest_tipo_list,
        'latest_cor_list': latest_cor_list,
    }
    return HttpResponse(template.render(context,request))

@login_required
def cadastrarRotulo(request):
    try:
        rotulo = Rotulo()
        rotulo.nome = request.POST['nome']
        rotulo.descricao = request.POST['descricao']        
        rotulo.cidadeFabricada = get_object_or_404(Cidade, pk=request.POST['cidade'])
        rotulo.fabricante = get_object_or_404(Fabricante, pk=request.POST['fabricante'])
        rotulo.tipo = get_object_or_404(Tipo, pk=request.POST['tipo'])
        rotulo.cor = get_object_or_404(Cor, pk=request.POST['cor'])
        rotulo.ibu = request.POST['ibu']
        rotulo.teorAlcoolico = request.POST['teorAlcoolico']        
        rotulo.save()
        SugestaoRotulo.gerarNotaCadastroRotulo(rotulo, request)
    except Exception as e:
        return HttpResponseRedirect(reverse('cloud:rotulo'))
    else:
        return HttpResponseRedirect(reverse('cloud:rotulo'))

@login_required
def toDeleteRotulo(request):
    try:
        rotulo = get_object_or_404(Rotulo, id=request.POST['id'])
        rotulo.delete()
    except:
        return HttpResponseRedirect(reverse('cloud:rotulo'))
    else:
        return HttpResponseRedirect(reverse('cloud:rotulo'))


@login_required
def cadastrarCartaCerveja(request):
    try:
        carta = Carta_Cerveja()
        carta.rotulo = get_object_or_404(Rotulo, pk=request.POST['rotulo'])
        carta.estabelecimento = get_object_or_404(Estabelecimento, pk=request.POST['estabelecimento'])
        carta.save()
    except:
        return HttpResponseRedirect(reverse('cloud:estabelecimento'))
    else:
        return HttpResponseRedirect(reverse('cloud:estabelecimento'))

@login_required
def toDeleteCarta(request):
    try:
        carta = get_object_or_404(Carta_Cerveja, id=request.POST['id'])
        carta.delete()
    except:
        return HttpResponseRedirect(reverse('cloud:estabelecimento'))
    else:
        return HttpResponseRedirect(reverse('cloud:estabelecimento'))

harmonazingbeer/cloud/views/view_Users.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from django.contrib.auth import authenticate, logout, login as authlogin
from django.template import Context, loader, RequestContext

from ..models.model_Person import *
from ..models.model_Address import Cidade

class UsuarioNewView(generic.ListView):
    model = Usuario
    template_name = 'cloud/cadUsuarioNew.html'
    context_object_name = 'latest_usuario_list'

    def get_queryset(self):
        return Usuario.objects.order_by('-nome')[:5]

    def get_context_data(self, *args, **kwargs):
        context = super(UsuarioNewView, self).get_context_data(*args, **kwargs)
        context['latest_cidade_list'] = Cidade.objects.order_by('nome')    
        return context 

def login(request):
    if (request.user.id):
        return HttpResponseRedirect(reverse('cloud:about'))

    if (request.POST):
        codUser = request.POST['codUsuario']
        senhaUser = request.POST['senhaUsuario'] 
        u = authenticate(username=codUser, password=senhaUser)

        if(u is not None):
            if (u.is_active):
                authlogin(request,u)

                if (request.POST.__contains__('next')):
                    return HttpResponseRedirect(request.POST['next'])
                
                return HttpResponseRedirect(reverse('cloud:about'))
        
        return HttpResponseRedirect(reverse('cloud:index'))

def sair(request):
    logout(request)
    return HttpResponseRedirect(reverse('cloud:index'))
    

harmonazingbeer/cloud/views/view_general.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.template import loader


class IndexView(generic.ListView):
    template_name = 'cloud/index.html'
    def get_queryset(self):
        return ''

class AboutView(generic.ListView):   
    template_name = 'cloud/about.html'
    def get_queryset(self):
        return ''

@login_required
def IndexOnView(request):        
    template = loader.get_template('cloud/indexOn.html')
    context = {}
    return HttpResponse(template.render(context, request))

harmonazingbeer/cloud/templates/cloud/about.html
{% extends "cloud/base.html" %} 
{% block content %}
{% load static %} 
    <img src="{%static '/imagens\index600400.jpg' %}" class="img-responsive" class="center-block">
{% endblock %}

harmonazingbeer/cloud/templates/cloud/base.html
<header>
    <title>Beer Sommelier</title>
</header>
<head>   
  {% load static %}    
  <link  href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet"/>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link  href="{% static '/css/customizedT.css' %}" rel="stylesheet"/>
</head>
<body class="body">    
  <h3><span class="textCabecalho"</span>Beer Sommelier</h3>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">      
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'cloud:indexOn' %}">Beer Sommelier </a>
        </div>                      
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">                      
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastros <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'cloud:cor' %}">Cor</a></li>
                            <li><a href="{% url 'cloud:fabricante' %}">Fabricante</a></li>
                            <li><a href="{% url 'cloud:rotulo' %}">Rótulo</a></li>
                            <li><a href="{% url 'cloud:tipo' %}">Tipo</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'cloud:comida' %}">Comida</a></li>
                            <li><a href="{% url 'cloud:prato' %}">Prato</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'cloud:cidade' %}">Cidade</a></li>
                            <li><a href="{% url 'cloud:estado' %}">Estado</a></li>
                            <li><a href="{% url 'cloud:pais' %}">País</a></li>
                            <li><a href="{% url 'cloud:regiao' %}">Região</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sugestão <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'cloud:sugestao' %}">Gerar Sugestão</a></li>
                            <li><a href="{% url 'cloud:nota' %}">Validar sugestão</a></li>
                            <li><a href="{% url 'cloud:peso' %}">Alterar Peso</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Estabelecimento <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'cloud:usuario' %}">Usuario</a></li>
                            <li><a href="{% url 'cloud:estabelecimento' %}">Estabelecimento</a></li>                            
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-right" action="{% url 'cloud:sair' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default" value="sair">LogOff</button>
                </form>                
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}           
    <script src='http://code.jquery.com/jquery-2.1.3.min.js'></script>
    <script src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js'></script>
    <script>$(function () {$('.dropdown-toggle').dropdown();});</script>
</body>

harmonazingbeer/cloud/templates/cloud/cadAcompanhamento.html
{% extends "cloud/base.html" %} 
{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Cadastro Acompanhamentos Prato: {{latest_prato.nome}}</h3>
    </div>
    <div class="panel-body">
        <form class="navbar-form navbar-left" action="{% url 'cloud:cadastrarAcompanhamento' %}" method="post">
            {% csrf_token %}
            <div class="form-group">                                    
                    <input type="hidden" name="id_Prato" value={{latest_prato.id}}>            
                    <label>Comida</label>            
                    <select class="form-control" name="id_Comida">
                        {% for comida in latest_comida_list %}
                        <option value={{comida.id}}>{{comida.nome}}</option>
                        {% endfor %}                        
                    </select>                
            </div>
            <button type="submit" class="btn btn-default" value="cadastrarAcompanhamento" >Gravar</button>    
        </form>
    </div>
</div>
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Acompanhamentos</div>  
        <!-- Table -->
    <table class="table">
        <thead> 
            <tr> 
                <th>Código</th> 
                <th>Prato</th>
                <th>Acompanhamento</th>
                <th>Excluir</th>
            </tr> 
        </thead>
        {% if latest_acompanhamento_list %}
            <tbody>                               
                {% for acompanhamento in latest_acompanhamento_list %}
                    <tr> 
                        <th scope="row"><var>{{acompanhamento.id}}</var></th> 
                        <td>{{ acompanhamento.prato.nome }}</td>          
                        <td>{{ acompanhamento.comida.nome }}</td>          
                        <td>
                            <form  action="{% url 'cloud:deleteAcompanhamento' %}" method="post">                                
                                {% csrf_token %}
                                <input type="hidden" name="id" value={{acompanhamento.id}}>
                                <button type="submit" class="btn btn-secondary btn-sm" value="deleteCadastro" >X</button>
                            </form>
                        </td>                
                    </tr> 
                {% endfor %}                
            </tbody>
        {% else %}    
            <div class="panel-body">
                <p>Não possui registros cadastrados</p>
            </div>
        {% endif %}            
    </table>
</div>
{% endblock %}

harmonazingbeer/cloud/templates/cloud/cadComida.html
{% extends "cloud/base.html" %} 
{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Cadastro Comida</h3>
    </div>
    <div class="panel-body">
        <form class="navbar-form navbar-left" action="{% url 'cloud:cadastrarComida' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Nome</label>
                <input type="text" class="form-control" name="nome" placeholder="Nome da comida">
                <label>Descrição</label>
                <input type="text" class="form-control" name="descricao" placeholder="Descrição da comida">                 
            </div>
            <button type="submit" class="btn btn-default" value="cadastrarComida" >Gravar</button>    
        </form>
    </div>
</div>
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Comidas</div>  
        <!-- Table -->
    <table class="table">
        <thead> 
            <tr> 
                <th>Código</th> 
                <th>Nome Comida</th>
                <th>Descrição</th>
                <th>Excluir</th>
            </tr> 
        </thead>
        {% if latest_comida_list %}
            <tbody>                               
                {% for comida in latest_comida_list %}
                    <tr> 
                        <th scope="row"><var>{{comida.id}}</var></th> 
                        <td>{{ comida.nome }}</td>          
                        <td>{{ comida.descricao }}</td>          
                        <td>
                            <form  action="{% url 'cloud:deleteComida' %}" method="post">                                
                                {% csrf_token %}
                                <input type="hidden" name="id" value={{comida.id}}>
                                <button type="submit" class="btn btn-secondary btn-sm" value="deleteCadastro" >X</button>
                            </form>
                        </td>                
                    </tr> 
                {% endfor %}                
            </tbody>
        {% else %}    
            <div class="panel-body">
                <p>Não possui registros cadastrados</p>
            </div>
        {% endif %}            
    </table>
</div>
{% endblock %}

harmonazingbeer/cloud/templates/cloud/cadCor.html
{% extends "cloud/base.html" %} 
{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Cadastro Cor</h3>
    </div>
    <div class="panel-body">
        <form class="navbar-form navbar-left" action="{% url 'cloud:cadastrarCor' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Nome</label>
                <input type="text" class="form-control" name="nome" placeholder="Nome da cor">
            </div>
            <button type="submit" class="btn btn-default" value="cadastrarCor" >Gravar</button>    
        </form>
    </div>
</div>
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Cores</div>  
        <!-- Table -->
    <table class="table">
        <thead> 
            <tr> 
                <th>Código</th> 
                <th>Nome Cor</th>
                <th>Excluir</th>
            </tr> 
        </thead>
        {% if latest_cor_list %}
            <tbody>                               
                {% for cor in latest_cor_list %}
                    <tr> 
                        <th scope="row"><var>{{cor.id}}</var></th> 
                        <td>{{ cor.nome }}</td>          
                        <td>
                            <form  action="{% url 'cloud:deleteCor' %}" method="post">                                
                                {% csrf_token %}
                                <input type="hidden" name="id" value={{cor.id}}>
                                <button type="submit" class="btn btn-secondary btn-sm" value="deleteCadastro" >X</button>
                            </form>
                        </td>                
                    </tr> 
                {% endfor %}                
            </tbody>
        {% else %}    
            <div class="panel-body">
                <p>Não possui registros cadastrados</p>
            </div>
        {% endif %}            
    </table>
</div>
{% endblock %}